export const UserData = [
  {
    "Record ID": 1,
    "Teacher Name": "Conrad Alexander",
    "Teacher Id": 1001,
    Department: "Finance",
    Student: 20,
    Status: "Suspended", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 2,
    "Teacher Name": "Sophia Martin",
    "Teacher Id": 1002,
    Department: "Mathematics",
    Student: 25,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 3,
    "Teacher Name": "Liam Johnson",
    "Teacher Id": 1003,
    Department: "Science",
    Student: 30,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 4,
    "Teacher Name": "Olivia Smith",
    "Teacher Id": 1004,
    Department: "Literature",
    Student: 18,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 5,
    "Teacher Name": "Ethan Brown",
    "Teacher Id": 1005,
    Department: "History",
    Student: 22,
    Status: "Suspended", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 6,
    "Teacher Name": "Ava Wilson",
    "Teacher Id": 1006,
    Department: "Physics",
    Student: 27,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 7,
    "Teacher Name": "Mason Garcia",
    "Teacher Id": 1007,
    Department: "Chemistry",
    Student: 20,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 8,
    "Teacher Name": "Isabella Martinez",
    "Teacher Id": 1008,
    Department: "Biology",
    Student: 19,
    Status: "Suspended", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 9,
    "Teacher Name": "Logan Anderson",
    "Teacher Id": 1009,
    Department: "Art",
    Student: 16,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 10,
    "Teacher Name": "Emma Thomas",
    "Teacher Id": 1010,
    Department: "Music",
    Student: 21,
    Status: "Blocked", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 11,
    "Teacher Name": "James Thompson",
    "Teacher Id": 1011,
    Department: "Dance",
    Student: 23,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 12,
    "Teacher Name": "Mia White",
    "Teacher Id": 1012,
    Department: "Computer Science",
    Student: 29,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 13,
    "Teacher Name": "Benjamin Harris",
    "Teacher Id": 1013,
    Department: "Physical Education",
    Student: 20,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 14,
    "Teacher Name": "Charlotte Clark",
    "Teacher Id": 1014,
    Department: "Sociology",
    Student: 22,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 15,
    "Teacher Name": "Lucas Rodriguez",
    "Teacher Id": 1015,
    Department: "Psychology",
    Student: 24,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 16,
    "Teacher Name": "Amelia Lewis",
    "Teacher Id": 1016,
    Department: "Philosophy",
    Student: 30,
    Status: "Suspended", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 17,
    "Teacher Name": "Oliver Lee",
    "Teacher Id": 1017,
    Department: "Economics",
    Student: 19,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 18,
    "Teacher Name": "Evelyn Walker",
    "Teacher Id": 1018,
    Department: "Statistics",
    Student: 28,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 19,
    "Teacher Name": "Henry Hall",
    "Teacher Id": 1019,
    Department: "Anthropology",
    Student: 26,
    Status: "Blocked", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 20,
    "Teacher Name": "Harper Allen",
    "Teacher Id": 1020,
    Department: "Geography",
    Student: 21,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 21,
    "Teacher Name": "Alexander Young",
    "Teacher Id": 1021,
    Department: "Statistics",
    Student: 22,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 22,
    "Teacher Name": "Ella King",
    "Teacher Id": 1022,
    Department: "Finance",
    Student: 24,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 23,
    "Teacher Name": "William Scott",
    "Teacher Id": 1023,
    Department: "Mathematics",
    Student: 30,
    Status: "Suspended", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 24,
    "Teacher Name": "Scarlett Green",
    "Teacher Id": 1024,
    Department: "Science",
    Student: 18,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 25,
    "Teacher Name": "Jacob Adams",
    "Teacher Id": 1025,
    Department: "Literature",
    Student: 23,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 26,
    "Teacher Name": "Sofia Nelson",
    "Teacher Id": 1026,
    Department: "History",
    Student: 29,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 27,
    "Teacher Name": "Jack Carter",
    "Teacher Id": 1027,
    Department: "Physics",
    Student: 21,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 28,
    "Teacher Name": "Grace Mitchell",
    "Teacher Id": 1028,
    Department: "Chemistry",
    Student: 20,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 29,
    "Teacher Name": "Michael Perez",
    "Teacher Id": 1029,
    Department: "Biology",
    Student: 24,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 30,
    "Teacher Name": "Zoe Roberts",
    "Teacher Id": 1030,
    Department: "Art",
    Student: 18,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 31,
    "Teacher Name": "Daniel Turner",
    "Teacher Id": 1031,
    Department: "Music",
    Student: 19,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 32,
    "Teacher Name": "Lily Phillips",
    "Teacher Id": 1032,
    Department: "Dance",
    Student: 22,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 33,
    "Teacher Name": "Matthew Campbell",
    "Teacher Id": 1033,
    Department: "Computer Science",
    Student: 30,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 34,
    "Teacher Name": "Megan Parker",
    "Teacher Id": 1034,
    Department: "Physical Education",
    Student: 25,
    Status: "Blocked", // Updated
    "All Details": "View More",
  },
  {
    "Record ID": 35,
    "Teacher Name": "Joshua Evans",
    "Teacher Id": 1035,
    Department: "Sociology",
    Student: 23,
    Status: "Suspended", // Updated
    "All Details": "View More",
  },

  {
    "Record ID": 36,
    "Teacher Name": "Hannah Edwards",
    "Teacher Id": 1036,
    Department: "Psychology",
    Student: 20,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 37,
    "Teacher Name": "Ryan Collins",
    "Teacher Id": 1037,
    Department: "Philosophy",
    Student: 23,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 38,
    "Teacher Name": "Avery Stewart",
    "Teacher Id": 1038,
    Department: "Economics",
    Student: 29,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 39,
    "Teacher Name": "Joshua Sanchez",
    "Teacher Id": 1039,
    Department: "Statistics",
    Student: 18,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 40,
    "Teacher Name": "Natalie Morris",
    "Teacher Id": 1040,
    Department: "Anthropology",
    Student: 25,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 41,
    "Teacher Name": "Samuel Rogers",
    "Teacher Id": 1041,
    Department: "Geography",
    Student: 21,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 42,
    "Teacher Name": "Luna Reed",
    "Teacher Id": 1042,
    Department: "Statistics",
    Student: 22,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 43,
    "Teacher Name": "Dylan Price",
    "Teacher Id": 1043,
    Department: "Finance",
    Student: 24,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 44,
    "Teacher Name": "Chloe James",
    "Teacher Id": 1044,
    Department: "Mathematics",
    Student: 30,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 45,
    "Teacher Name": "Eli Bennett",
    "Teacher Id": 1045,
    Department: "Science",
    Student: 19,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 46,
    "Teacher Name": "Victoria Hughes",
    "Teacher Id": 1046,
    Department: "Literature",
    Student: 23,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 47,
    "Teacher Name": "John Ortiz",
    "Teacher Id": 1047,
    Department: "History",
    Student: 26,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 48,
    "Teacher Name": "Ellie Fisher",
    "Teacher Id": 1048,
    Department: "Physics",
    Student: 20,
    Status: "Inactive",
    "All Details": "View More",
  },
  {
    "Record ID": 49,
    "Teacher Name": "Carter Turner",
    "Teacher Id": 1049,
    Department: "Chemistry",
    Student: 27,
    Status: "Active",
    "All Details": "View More",
  },
  {
    "Record ID": 50,
    "Teacher Name": "Lily Rivera",
    "Teacher Id": 1050,
    Department: "Biology",
    Student: 29,
    Status: "Inactive",
    "All Details": "View More",
  },
];
